permissions:
    id-token: write # This is required for requesting the JWT
    contents: read # This is required for actions/checkout
  
  name: release
  
  on:
    push:
      branches:
        - cole/witness
  
  jobs:
    build-docker-server:
      runs-on: "ubuntu-22.04"
  
      steps:
        - name: Checkout
          uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
          with:
            fetch-depth: 0
  
        - name: Setup KO
          uses: imjasonh/setup-ko@v0.6
          env:
            KO_DOCKER_REPO: ghcr.io/github.com/testifysec/pipeline-entrypoint
        - name: Login to GHCR
          env:
            AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          run: |
            echo "${AUTH_TOKEN}" | ko login ghcr.io --username dummy --password-stdin
  
        - name: Build Entrypoint
          uses: testifysec/witness-run-action@v0.1.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
            KO_DOCKER_REPO: ghcr.io/github.com/testifysec/pipeline-entrypoint
          with:
            enable-sigstore: true
            enable-archivista: true
            trace: true
            step: "build"
            attestations: "git github oci"
            command: ko build --bare --tarball entrypoint.tar --sbom-dir . ./cmd/entrypoint
  
        - name: "Upload Server artifact"
          uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
          with:
            name: entrypoint
            path: entrypoint.tar
            retention-days: 5