permissions:
    id-token: write # This is required for requesting the JWT
    contents: read # This is required for actions/checkout
  
name: release


on:
    push:
      branches:
        - '*'
jobs:
    build-entrypoint:
      runs-on: "ubuntu-22.04"
  
      steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.20.6
        
        - name: Checkout
          uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
          with:
            fetch-depth: 0
      
      
        - uses: actions/cache@v2
          with:
           path: |
             ~/go/pkg/mod
             ~/.cache/go-build
           key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
           restore-keys: |
              ${{ runner.os }}-go-

  
        - name: Setup KO
          uses: imjasonh/setup-ko@v0.6
          env:
            KO_DOCKER_REPO: ghcr.io/github.com/testifysec/pipeline-entrypoint
  
        - name: Login to GHCR
          env:
            AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          run: |
            echo "${AUTH_TOKEN}" | ko login ghcr.io --username dummy --password-stdin
  
        - name: Build Entrypoint
          uses: testifysec/witness-run-action@v0.1.3
          env:
            GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
            GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
            KO_DOCKER_REPO: ghcr.io/github.com/testifysec/pipeline-entrypoint
          with:
            enable-sigstore: true
            enable-archivista: true
            trace: true
            step: "build"
            attestations: "git github oci"
            command: ko build --tarball entrypoint.tar --sbom-dir . ./cmd/entrypoint
  